### ISSUE TITLE
Using AI for small tasks

### ISSUE THREAD

**Issue by pawlean** [gitpod-io/community-office-hours#30]
As discussed in [our community sync](https://www.notion.so/gitpod/Community-Sync-c5a6d328974e4ae096a01f6182cda713?pvs=4#a666fe58619f465b9a5c80ef4a2be8a7), we should try and use AI to automate smaller tasks including sorting through `gitpod-user-activity` comments that could be useful for product feedback and for identifying issues and triaging them to the correct engineering team.

```[tasklist]
### Tasks
- [ ] https://github.com/gitpod-io/community/issues/35
- [ ] https://github.com/gitpod-io/community/issues/34
- [ ] https://github.com/gitpod-io/community/issues/33
- [ ] https://github.com/gitpod-io/community/issues/32
- [ ] https://github.com/gitpod-io/community/issues/31
```

**Comment by axonasif** [comment]
Thanks for opening this issue @pawlean! I created separate ["task" issues](https://github.com/gitpod-io/community/issues/30#icon-button-69bd0a78-6c6f-4d7b-852f-da85f288ecbf) to split up the work.

**Comment by axonasif** [comment]
### Update

Initial work for #33 and #34 is done: https://github.com/axonasif/glu

It's still incomplete, I'll probably be able to get it completed for the first two tasks next week.

Some private docs about authentication: [here](https://www.notion.so/gitpod/Glu-bot-226504f6aa1b4b89a2fe5ff974c2aa52)

**Comment by axonasif** [comment]
Project update: the first three tasks are now complete.

https://github.com/gitpod-io/community/issues/32 will be next.
