### ISSUE TITLE
Orbit Improvements

### ISSUE THREAD

**Issue by pawlean** [gitpod-io/community-office-hours#36]
As we discussed in our recent community sync meeting [[1](https://www.notion.so/gitpod/Community-Sync-ca1a1b88f9214f24b579aef8aee6c079?pvs=4#53b8579dbd084d05aa9b83d8302a2c8e)], we should use Orbit more to improve our community engagement and visibility. Some ideas:

```[tasklist]
### Tasks
- [ ] https://github.com/gitpod-io/community/issues/37
- [ ] https://github.com/gitpod-io/community/issues/38
- [ ] https://github.com/gitpod-io/community/issues/39
```
